### PR TITLE
Missing slash module to run test

### PR DESCRIPTION
**Pull request by MrBr**

### CODE REVIEW

**Comment by lelandrichardson** [comment]
@MrBr what is the slash module? why is this needed? is this a windows thing? please provide more info. Thanks!

**Comment by MrBr** [comment]
Slash definition from npmjs.com "Convert Windows backslash paths to slash paths".

Again, I am not sure why is this module used for in this particular case, it seems to me that some dependency requires it but doesn't have it under devDep.

I've done little research and found that babel-core requires slash but for some reason when doing npm install for the first time, slash module doesn't get installed. Running npm install second time solves problem.

I don't understand this behaviour, and not sure if it is just in my case or it is general problem.
This pull request is not solution, but maybe this case be noted somewhere if someone else runs to problem like this.

**Comment by marclundgren** [comment]
@lelandrichardson I think @MrBr sent this PR because `npm test` fails.

```
☁  enzyme-example-react-native [master] npm test

> enzyme-example-react-native@0.1.0 test /Users/marc/Dev/enzyme-example-react-native
> mocha --require react-native-mock/mock.js --compilers js:babel-core/register --recursive test/*.js

module.js:341
    throw err;
    ^

Error: Cannot find module 'slash'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/marc/Dev/enzyme-example-react-native/node_modules/babel-core/lib/util.js:49:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/marc/Dev/enzyme-example-react-native/node_modules/babel-core/lib/api/node.js:25:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/marc/Dev/enzyme-example-react-native/node_modules/babel-core/index.js:1:80)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/marc/Dev/enzyme-example-react-native/node_modules/babel-register/lib/node.js:27:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/marc/Dev/enzyme-example-react-native/node_modules/babel-core/register.js:2:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /Users/marc/Dev/enzyme-example-react-native/node_modules/mocha/bin/_mocha:302:3
    at Array.forEach (native)
    at Object.<anonymous> (/Users/marc/Dev/enzyme-example-react-native/node_modules/mocha/bin/_mocha:296:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
npm ERR! Test failed.  See above for more details.
```

**Comment by lelandrichardson** [comment]
Closing due to #3

**Pull request closed without merging**
